# Add this service to your existing docker-compose.yml file

  discord-bot:
    image: discord-bot
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - MONGODB_TOKEN=${MONGODB_TOKEN}
      - MINECRAFT_SERVER_IP=${MINECRAFT_SERVER_IP}
      - CLIENT_ID=${MINECRAFT_SERVER_IP}
      - NODE_ENV=production
    networks:
      - your-network-name
