# Add this service to your existing docker-compose.yml file

  discord-bot:
    image: your-registry/discord-bot:latest
    container_name: discord-bot
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - MONGODB_TOKEN=${MONGODB_TOKEN}
      - MINECRAFT_SERVER_IP=${MINECRAFT_SERVER_IP}
      - NODE_ENV=production
    networks:
      - your-network-name
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"